### ISSUE TITLE
Flash of Unstyled Content

### ISSUE THREAD

**Issue by akircher** [aurelia/animator-css#11]
I don't see FOUC on the default skeleton-nav app, which only uses au-enter animations.  However, if I add au-leave animations as well, then I get a FOUC in between page transitions.  Unfortunately, I am not sure if the flash is the unstyled page leaving or the unstyled page entering.

**Comment by zewa666** [comment]
Could you post an example including the css markup?

**Comment by akircher** [comment]
http://plnkr.co/edit/dX5K8O?p=preview

**Comment by zewa666** [comment]
@akircher hi, i've pushed a new branch `animation-done-class`. If you could check this one out and see whether it solves your problem that'd be awesome. What it does is to set an `au-entered` or `au-left` class on elements after successful animations. This feature is opt-in, means in order to use it you'd have to configure it manually like this in your manual bootstrapping:

```javascript
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-animator-css', (animator) => {
      animator.useAnimationDoneClasses = true // <-- activate opt-in feature
      
      // these here are optional, defaults are au-entered and au-left
      animator.animationEnteredClass = 'my-custom-entered-class-name';
      animator.animationLeftClass = 'my-custom-left-class-name';
    });

  aurelia.start().then(a => a.setRoot());
}
```
We might need to adjust the exact moment of when to place those elements but its a start. So for your example please try setting the left class on your element and inside there place a css rule for `opacity: 0 !important;`

**Comment by akircher** [comment]
Not sure if this is the right approach.  My need is just a place holder for issue #7, I want to have one view leave and then another view enter.  Right now, I am doing that sequentially - rather than concurrently - resulting in a flash.  Maybe it's best to wait and see that solution before building in a configuration step.
