### ISSUE TITLE
Cleanup temporary class name not work

### ISSUE THREAD

**Issue by npelletm** [aurelia/animator-css#29]
With a simple ```<div class="fa fa-spinner fa-spin"  show.bind="isWaiting"></div>``` on the first load with ```isWaiting=false```, the class remains ```aurelia-hide-add``` in place of ```aurelia-hide```
I've this issue on IE11

Here, https://github.com/aurelia/animator-css/blob/master/src/animator.js#L542 the test < 0 seems to be bogus, with a  >=0  test it works.

There are the same potential issue in these lines : 
https://github.com/aurelia/animator-css/blob/master/src/animator.js#L264
https://github.com/aurelia/animator-css/blob/master/src/animator.js#L370
https://github.com/aurelia/animator-css/blob/master/src/animator.js#L458

Additional infos :
Same issue on chrome 46.
With a ```setTimeout(() => this.isWaiting = false, 100)``` it works

Additional infos (2) : read this first :)
the ```fa-spin``` animation from font awesome is an infinite duration animation, with a finite animation duration it works, this is the issue. My initial analysis was wrong !

**Comment by EisenbergEffect** [comment]
@zewa666 Please take a look into this. Thanks!

**Comment by Mordred** [comment]
Same here, with this HTML:

```html
<button type="button" disabled.bind="processing" class="btn btn-primary" click.trigger="create()">
  <span show.bind="processing">
    <i class="fa fa-spin fa-spinner"></i>&nbsp;<span>Saving</span><span>…</span>
  </span>
  <span show.bind="!processing">
    Save
  </span>
</button>
```

If you switch `processing` to true in one tick and then to false in another. Both spans will have 'aurelia-hide' class.

Demo:
http://plnkr.co/edit/hyV1AIjZBx2B4ZHLFAIA?p=preview

**Comment by zewa666** [comment]
ok so the issue comes down to this change: https://github.com/aurelia/templating-resources/commit/019a2062449ecba8b8091889c358dfc425ae5424

reverting this to `this.element.classList` operations fixes it for me. @Mordred can I ask you to manually change that (jspm_packages/npm/aurelia-templating-resources.../show.js) and verify that this works for you as well? If so we know where to fix the issue.

**Comment by Mordred** [comment]
@zewa666 Yes, this has fixed the button, but I think this should be fixed at animator level. Problem is that **animationstart** and **animationend** can bubble from children even if there is no animation for animated element itself.

**Comment by zewa666** [comment]
you're right @Mordred. The issue is all about the timeout and not being able to identify which's event (add or remove) was fired.

In your example try increasing the timeout high enough (e.g. 55) and it works again. So I think we need to find a way to tie the anmiationstart/end event not only to an element but also the animation method itself.

**Comment by zewa666** [comment]
@Mordred can you test the new release please? It should now properly cleanup all classes.

**Comment by Mordred** [comment]
@zewa666 Yes, it is working now. Classes are OK. 

Sometimes the 50ms delay is visible - both spans are hidden. How you get that timeout number?

**Comment by EisenbergEffect** [comment]
@zewa666 I think this is ok as a quick fix. I'm not sure we want a timeout as a long-term solution. Can you look at an alternate way to address this?

**Comment by zewa666** [comment]
Well if we work with CSS3-Animations we're always bound to the timeout, since we don't know when the animation will trigger. The idea is that you set a specific css-class to an element and the element will trigger a DOM-Event. now that should work quite fast, but I realized sometimes it takes a while. 50 was just a guessing by myself, it should also work with lower values. Thats why it's modifiable.

Also the CSS Animator is really meant for simple animations and no complex timing scenarios. That's what Velocity or GreenSock is best at.

**Comment by npelletm** [comment]
Latest beta 1.0.1 version solve the issue

**Comment by Einarsson** [comment]
Still have issues like this with latest framework (updated it all today). 

http://i.imgur.com/CF44oSy.png

As you can see here, account.isBusy is false but tr-row is still showing.

This is a case where the account loads it's transactions, so when loading it sets busy and when http-call is done it sets isbusy = false again. Sometimes doesnt, work, sometimes it does.
