### ISSUE TITLE
Animator interfering with other CSS Transitions

### ISSUE THREAD

**Issue by aqm5181** [aurelia/animator-css#47]
Plunker Example:
http://plnkr.co/edit/ZTqND2?p=preview

Transitions applied to elements that do not have the au-animate attribute on them are affected by the animator in that the element is hidden immediately after the transition has completed. Bug only appears where "show.bind" condition is applied to the same element. The same issue doesnt seem to occur with if.bind.

Simple example above where a fadeIn affect ends with the element being hidden where show.bind is used.

Once the element is hidden, the transition effect no longer works if re-applied.

Bug also present in latest version of aurelia animator (1.0.0-beta.1.2.0).

Thanks

**Comment by EisenbergEffect** [comment]
@zewa666 Can you take a look?

**Comment by z-brooks** [comment]
@EisenbergEffect @zewa666 Pull request open that should fix it.  I've tested it in a fresh skeleton without problems.

The event handlers were hanging around from the initial setup of the `show` attribute (since __aurelia-hide__ is not animated). `show` would then remove __aurelia-hide__ (when true) and the handlers would fire for the fade animation causing __aurelia-hide__ to be added again (from the `addClass` *animationend* callback).

I didn't see any issues related to it but this could also happen in the `leave` and `enter` methods if they were called when no animatable class was defined (au-enter/leave[-active]).
